-- Run this in Supabase SQL Editor (Dashboard → SQL Editor) to create the table for message threading.
-- Optional: only needed if you set SUPABASE_URL and SUPABASE_SERVICE_KEY.

create table if not exists public.message_threads (
  id bigint generated by default as identity primary key,
  user_chat_id bigint not null,
  group_chat_id text not null,
  group_message_id bigint not null,
  created_at timestamptz default now()
);

create index if not exists idx_message_threads_lookup
  on public.message_threads (group_chat_id, group_message_id);

-- RLS: with no policies, only the service_role key (used by your app) can access the table.
alter table public.message_threads enable row level security;
